# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b4e0661f5cf19ade9c2d7bad6e8163eeaaef065f4079d1e2d919cdac2ecd986ce066e28b03a75f00347c8b8a704613a40ed92ed8cade3defefa8c0d50c51a0a

test:
  secret_key_base: bad03d0974788a75a125839379192d49643cbf8ee13917b5d355d50ba69e3cb2d2d19b9119c60d4d7f99ae271ff3016159729f43a36e12c6a9798ce8412e8377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
